### ISSUE TITLE
Console error on last MoPub SDK

### ISSUE THREAD

**Issue by catalincraciun** [flurry/FlurryAdapterForMoPubiOS#3]
MoPub is complaining at runtime, when an ad request is made: 'Could not find renderer configuration for custom event class'. Could you help me with this? In the past I was using the previous version of FlurryAdapter with MoPub 3.9 and everything was working perfect, since I have updated to MoPub 4.4 with FlurryAdapter 7.2.1, this issue keeps coming up. Please see the screenshot attached below.

Thank you in advance.

<img width="906" alt="screen shot 2015-12-15 at 6 43 57 pm" src="https://cloud.githubusercontent.com/assets/5362999/11817346/333ebe4c-a35d-11e5-84ec-9a5a488e8b3c.png">

**Comment by t3chno** [comment]
You have to add supportedCustomEvents on MPStaticNativeAdRenderer.m

It should look like this;
config.supportedCustomEvents = @[@"MPMoPubNativeCustomEvent", @"FacebookNativeCustomEvent", @"MoPubNativeAdapterMobFox", @"InMobiNativeCustomEvent", @"AppLovinNativeCustomEvent", @"MillennialNativeCustomEvent", @"FlurryNativeCustomEvent"];

**Comment by ugonna** [comment]
Thanks, @t3chno, for the answer. Apologies, @catalincraciun, for letting this issue fall through the cracks.

I assume this issue has long been resolved and will close it. Let us know if it still persists.

**Comment by catalincraciun** [comment]
No problem. Solved the issue back in those days but forgot to come back with a follow-up. @t3chno That's right, that was the correct solution.

**Comment by t3chno** [comment]
This topic can help others also for _"MOPUB: Could not find renderer configuration for custom event class"_ problem.
